name: venv
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.8
  - cudatoolkit=10.1
  - pytorch::pytorch==1.7.1
  - pytorch::torchvision==0.8.2
  - imageio==2.9.0
  - matplotlib==3.3.3
  - numpy==1.19.5
  - pandas==1.2.0
  - Pillow==8.1.0
  - PyYAML==5.3.1
  - scikit-image==0.18.1
  - scikit-learn==0.24.0
  - scipy==1.6.0
  - tqdm==4.56.0
  - imageio-ffmpeg==0.4.3
