name: venv10
channels:
  - pytorch
dependencies:
  - python=3.7
  - cudatoolkit=10.1
  - pytorch==1.0.0
  - torchvision==0.2.1
  - Cffi==1.11.5
  - Cloudpickle==0.5.3
  - Cycler==0.10.0
  - Dask==0.18.2
  - Decorator==4.3.0
  - Imageio==2.3.0
  - Kiwisolver==1.0.1
  - Matplotlib==2.2.2
  - Networkx==2.1
  - Numpy==1.15.0
  - Pandas==0.23.4
  - Pillow==5.2.0
  - Pycparser==2.18
  - Pyparsing==2.2.0
  - Python-dateutil==2.7.3
  - Pytz==2018.5
  - PyWavelets==0.5.2
  - PyYAML==5.1
  - Scikit-image==0.14.0
  - Scikit-learn==0.19.2
  - Scipy==1.1.0
  - Six==1.11.0
  - Toolz==0.9.0
  - Tqdm==4.24.0
